# mkdocs.yml
site_name: Speechain
site_description: Documentation for Speechain Toolkit

repo_url: https://github.com/bagustris/speechain

theme:
  name: "material"
  favicon: img/favicon.ico
  logo: img/speechain_inverted.png

plugins:
  - search
  - autorefs
  - gen-files:
        scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [speechain, .]


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - md_in_html

extra_javascript:
  # - javascripts/mathjax.js
  # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - css/code_select.css
  - https://unpkg.com/katex@0/dist/katex.min.css

nav:
  - index.md
  - handbook.md
  - datasets.md
  - recipes.md
  - Tutorials:
    - TTS LJSpeech: tts_ljspeech_tutorial.md
  - asr.md
  - tts.md
  - criterion.md
  - dataset.md
  - iterator.md
  - model.md
  - module.md
  - optim_sche.md
  - tokenizer.md
  - Reference: reference/ 
